#my_string = input("введите ваше имя: ")
#length = len(my_string)
#print(f"количество символов в строке: {length}")
#my_string = input("введите ваше имя: ".upper())
#print(my_string)
#my_string = input("введите ваше имя: ".lower())
#print(my_string)
#my_string = input("введите ваше имя:")
#print("введите ваше имя".replace(" ", ""))
#my_string = input("введите ваше имя: ")
#print(my_string[0])
my_string = input("введите ваше имя: ")
print(my_string[-1])